name: Gh-Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Build and Deploy to GitHub Pages
        run: |
          flutter config --enable-web
          flutter build web --release --web-renderer=auto --no-tree-shake-icons --base-href "/Old-Portfolio/"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git --work-tree build/web commit -m "Automatic deployment by GitHub Actions"
          git push origin HEAD:gh-pages --force
        working-directory: ${{ github.workspace }}
        shell: bash
